version = 1

test_patterns = ["tests/*"]

exclude_patterns = ["projet/templates/*.html", "docs/*"]

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "prettier"
enabled = true